# Generated by Django 4.0.4 on 2022-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_site_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
