# Generated by Django 4.0.4 on 2022-08-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_phone_position_peoplerelationship_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='peoplerelationship',
        ),
        migrations.AddField(
            model_name='people',
            name='peoplerelationship',
            field=models.ManyToManyField(to='addresses.peoplerelationship'),
        ),
        migrations.AlterField(
            model_name='peoplerelationship',
            name='name_relationship',
            field=models.CharField(choices=[('VO', 'Vợ'), ('CH', 'Chồng'), ('CO', 'Con'), ('BV', 'Bố Vợ'), ('MV', 'Mẹ Vợ'), ('BC', 'Bố Chồng'), ('MC', 'Mẹ Chồng'), ('BR', 'Bố Ruột'), ('MR', 'Mẹ Ruột')], max_length=2),
        ),
    ]
