# Generated by Django 4.0.4 on 2022-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_city_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
